# Generated by Django 3.2 on 2021-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile_background',
            field=models.ImageField(blank=True, default='uploads/covers/default.jpg', upload_to='uploads/covers'),
        ),
    ]
