# Generated by Django 3.2 on 2021-05-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_grouppost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupposts', to='groups.group'),
        ),
    ]
