# Generated by Django 3.2 on 2021-05-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_grouppost_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_on']},
        ),
    ]
