# Generated by Django 3.2 on 2021-05-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20210529_1632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
    ]
