# Generated by Django 3.2 on 2021-05-31 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0012_alter_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
