# Generated by Django 3.2 on 2021-05-31 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0013_group_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ban',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_ban', to=settings.AUTH_USER_MODEL),
        ),
    ]
