# Generated by Django 3.2 on 2021-06-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_group_ban'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppost',
            unique_together=set(),
        ),
    ]
