# Generated by Django 3.2 on 2021-06-01 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_alter_grouppost_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='joined_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
