# Generated by Django 3.2 on 2021-06-01 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0016_groupmember_joined_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
