# Generated by Django 3.2 on 2021-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_alter_grouppost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
