# Generated by Django 3.2 on 2021-07-05 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0019_auto_20210602_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ban',
            field=models.ManyToManyField(blank=True, related_name='group_ban', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='group_moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'group')},
        ),
    ]
