# Generated by Django 3.2.6 on 2021-08-15 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20210705_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='image',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/video_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
